server:
  port: 8081

spring:
  profiles:
    active: developer
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      cache:
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    properties:
      hibernate:
        generate_statistics: true
        use_sql_comments: true
        format_sql: true

conveyor:
  service:
    url: http://localhost:8080

logging:
  level:
    ROOT: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
